export const SET_BALANCE_INIT = 'SET_BALANCE_INIT';
export const SET_BALANCE_LOADING = 'SET_BALANCE_LOADING';
export const SET_BALANCE_LOADED = 'SET_BALANCE_LOADED';
export const SET_BALANCE_FAILED = 'SET_BALANCE_FAILED';
export const SET_BALANCE = 'SET_BALANCE';
